/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-display)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      colors: {
        'th-bg-primary': 'var(--bg-primary)',
        'th-bg-secondary': 'var(--bg-secondary)',
        'th-bg-tertiary': 'var(--bg-tertiary)',
        'th-bg-elevated': 'var(--bg-elevated)',
        'th-border': 'var(--border)',
        'th-border-hover': 'var(--border-hover)',
        'th-separator': 'var(--separator)',
        'th-text-primary': 'var(--text-primary)',
        'th-text-secondary': 'var(--text-secondary)',
        'th-text-muted': 'var(--text-muted)',
        'th-hover': 'var(--hover)',
        'th-accent': 'var(--accent)',
        'th-accent-light': 'var(--accent-light)',
        'th-accent-soft': 'var(--accent-soft)',
        'th-accent-bg': 'var(--accent-bg)',
        'th-accent-bg-strong': 'var(--accent-bg-strong)',
        'th-success': 'var(--success)',
        'th-warning': 'var(--warning)',
        'th-error': 'var(--error)',
        'th-error-bg': 'var(--error-bg)',
        'th-danger': 'var(--danger)',
        'th-danger-bg': 'var(--danger-bg)',
        'th-node-filled': 'var(--node-filled)',
        'th-node-partial': 'var(--node-partial)',
        'th-node-empty': 'var(--node-empty)',
        'th-input-bg': 'var(--input-bg)',
        'th-input-border': 'var(--input-border)',
        'th-user-bubble': 'var(--user-bubble-bg)',
        'th-user-bubble-text': 'var(--user-bubble-text)',
        'th-assistant-bubble': 'var(--assistant-bubble-bg)',
        'th-assistant-bubble-text': 'var(--assistant-bubble-text)',
        'th-ribbon-bg': 'var(--ribbon-bg)',
        'th-ribbon-text': 'var(--ribbon-text)',
        'th-ribbon-border': 'var(--ribbon-border)',
        'th-depth-guide': 'var(--depth-guide)',
        'th-badge-published-bg': 'var(--badge-published-bg)',
        'th-badge-published-text': 'var(--badge-published-text)',
        'th-badge-published-border': 'var(--badge-published-border)',
        'th-badge-published-dot': 'var(--badge-published-dot)',
        'th-badge-draft-bg': 'var(--badge-draft-bg)',
        'th-badge-draft-text': 'var(--badge-draft-text)',
        'th-badge-draft-border': 'var(--badge-draft-border)',
        'th-badge-draft-dot': 'var(--badge-draft-dot)',
        'th-badge-empty-bg': 'var(--badge-empty-bg)',
        'th-badge-empty-text': 'var(--badge-empty-text)',
        'th-badge-empty-border': 'var(--badge-empty-border)',
        'th-badge-empty-dot': 'var(--badge-empty-dot)',
      },
      boxShadow: {
        'th': 'var(--shadow)',
        'th-md': 'var(--shadow-md)',
        'th-lg': 'var(--shadow-lg)',
        'th-float': 'var(--shadow-float)',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'soft': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        'spring-in': {
          '0%': { opacity: '0', transform: 'translateY(4px) scale(0.96)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '1' },
        },
        'cursor-scan': {
          '0%, 100%': { transform: 'translateY(0)', opacity: '0.4' },
          '50%': { transform: 'translateY(8px)', opacity: '1' },
        },
      },
      animation: {
        'spring-in': 'spring-in 0.22s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'fade-in': 'fade-in 0.18s ease-out',
        'pulse-dot': 'pulse-dot 1.4s ease-in-out infinite',
        'cursor-scan': 'cursor-scan 1.2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
