// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AiConfig struct {
	ID        int64
	Provider  string
	ModelName string
	ApiKey    string
	IsActive  sql.NullInt64
	Config    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Conversation struct {
	ID          int64
	TopicID     sql.NullInt64
	ExerciseID  sql.NullInt64
	ContextType sql.NullString
	Title       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Exercise struct {
	ID                      int64
	TopicID                 int64
	Type                    sql.NullString
	Title                   string
	Description             sql.NullString
	Difficulty              sql.NullString
	SortOrder               sql.NullInt64
	Tags                    sql.NullString
	Hints                   sql.NullString
	SolutionOutline         sql.NullString
	SolutionDetail          sql.NullString
	CommonErrors            sql.NullString
	TimeComplexityExpected  sql.NullString
	SpaceComplexityExpected sql.NullString
	SampleCode              sql.NullString
	CreatedAt               sql.NullTime
	UpdatedAt               sql.NullTime
}

type LearningRecord struct {
	ID             int64
	TopicID        sql.NullInt64
	ExerciseID     sql.NullInt64
	Status         sql.NullString
	MasteryLevel   sql.NullInt64
	Notes          sql.NullString
	LastReviewedAt sql.NullTime
	ReviewCount    sql.NullInt64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Message struct {
	ID             int64
	ConversationID int64
	Role           string
	Content        string
	ModelProvider  sql.NullString
	TokenCount     sql.NullInt64
	ToolCalls      sql.NullString
	CreatedAt      sql.NullTime
}

type Plan struct {
	ID                  string          `json:"id"`
	ConversationID      *int64          `json:"conversation_id,omitempty"`
	Reasoning           string          `json:"reasoning"`
	Status              string          `json:"status"`
	Outline             json.RawMessage `json:"outline,omitempty"`
	PhaseIndex          *int64          `json:"phase_index,omitempty"`
	TotalPhases         *int64          `json:"total_phases,omitempty"`
	Actions             []PlanAction    `json:"actions,omitempty"`
	CreatedAt           string          `json:"created_at"`
	ExecutedAt          *string         `json:"executed_at,omitempty"`
	FocusPageID         *int64          `json:"focus_page_id,omitempty"`
	CalibrationQuestion json.RawMessage `json:"calibration_question,omitempty"`
	Stage               string          `json:"stage,omitempty"`
}

type PlanAction struct {
	ID        string          `json:"id"`
	PlanID    string          `json:"plan_id"`
	Type      string          `json:"type"`
	Params    json.RawMessage `json:"params"`
	DependsOn json.RawMessage `json:"depends_on"`
	Status    string          `json:"status"`
	Result    *string         `json:"result,omitempty"`
	Error     sql.NullString  `json:"error,omitempty"`
	SortOrder int64           `json:"sort_order"`
	CreatedAt string          `json:"created_at"`
}

type Topic struct {
	ID             int64
	ParentID       sql.NullInt64
	Name           string
	Slug           string
	Description    sql.NullString
	KeyPoints      sql.NullString
	Content        sql.NullString
	CodeExamples   sql.NullString
	CommonMistakes sql.NullString
	Difficulty     sql.NullString
	SortOrder      sql.NullInt64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type WikiLog struct {
	ID        int64
	Action    string
	PageID    sql.NullInt64
	PageTitle string
	PagePath  sql.NullString
	Source    string
	Summary   sql.NullString
	CreatedAt time.Time
}

type WikiPage struct {
	ID                 int64
	Title              string
	Slug               string
	PageType           string
	Content            string
	Tags               sql.NullString
	ParentID           sql.NullInt64
	Path               string
	Links              string
	Backlinks          string
	ContentStatus      string
	SortOrder          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Summary            string
	SummaryStatus      string
	SummaryGeneratedAt sql.NullTime
	SummaryContentHash sql.NullString
	LinkCount          int64
	BacklinkCount      int64
	TagsNormalized     string
}
