// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package model

import (
	"database/sql"
)

type AiConfig struct {
	ID        int64
	Provider  string
	ModelName string
	ApiKey    string
	IsActive  sql.NullInt64
	Config    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Conversation struct {
	ID          int64
	TopicID     sql.NullInt64
	ExerciseID  sql.NullInt64
	ContextType sql.NullString
	Title       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Exercise struct {
	ID                      int64
	TopicID                 int64
	Type                    sql.NullString
	Title                   string
	Description             sql.NullString
	Difficulty              sql.NullString
	Tags                    sql.NullString
	Hints                   sql.NullString
	SolutionOutline         sql.NullString
	TimeComplexityExpected  sql.NullString
	SpaceComplexityExpected sql.NullString
	SampleCode              sql.NullString
	CreatedAt               sql.NullTime
	UpdatedAt               sql.NullTime
}

type LearningRecord struct {
	ID             int64
	TopicID        sql.NullInt64
	ExerciseID     sql.NullInt64
	Status         sql.NullString
	MasteryLevel   sql.NullInt64
	Notes          sql.NullString
	LastReviewedAt sql.NullTime
	ReviewCount    sql.NullInt64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Message struct {
	ID             int64
	ConversationID int64
	Role           string
	Content        string
	ModelProvider  sql.NullString
	TokenCount     sql.NullInt64
	CreatedAt      sql.NullTime
}

type Topic struct {
	ID          int64
	ParentID    sql.NullInt64
	Name        string
	Slug        string
	Description sql.NullString
	KeyPoints   sql.NullString
	Difficulty  sql.NullString
	SortOrder   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
