// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package model

import (
	"context"
	"database/sql"
	"time"
)

const batchUpdateTopicContent = `-- name: BatchUpdateTopicContent :exec
UPDATE topics SET content = ?, code_examples = ?, common_mistakes = ?, updated_at = CURRENT_TIMESTAMP WHERE slug = ?
`

type BatchUpdateTopicContentParams struct {
	Content        sql.NullString
	CodeExamples   sql.NullString
	CommonMistakes sql.NullString
	Slug           string
}

func (q *Queries) BatchUpdateTopicContent(ctx context.Context, arg BatchUpdateTopicContentParams) error {
	_, err := q.db.ExecContext(ctx, batchUpdateTopicContent,
		arg.Content,
		arg.CodeExamples,
		arg.CommonMistakes,
		arg.Slug,
	)
	return err
}

const batchUpdateWikiPagePath = `-- name: BatchUpdateWikiPagePath :exec
UPDATE wiki_pages SET path = REPLACE(path, ?1, ?2) WHERE path LIKE ?3 || '%'
`

type BatchUpdateWikiPagePathParams struct {
	OldPrefix  string
	NewPrefix  string
	LikePrefix sql.NullString
}

func (q *Queries) BatchUpdateWikiPagePath(ctx context.Context, arg BatchUpdateWikiPagePathParams) error {
	_, err := q.db.ExecContext(ctx, batchUpdateWikiPagePath, arg.OldPrefix, arg.NewPrefix, arg.LikePrefix)
	return err
}

const countWikiPages = `-- name: CountWikiPages :one
SELECT COUNT(*) FROM wiki_pages
`

func (q *Queries) CountWikiPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWikiPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWikiPagesByStatus = `-- name: CountWikiPagesByStatus :one
SELECT COUNT(*) FROM wiki_pages WHERE content_status = ?
`

func (q *Queries) CountWikiPagesByStatus(ctx context.Context, contentStatus string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWikiPagesByStatus, contentStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIConfig = `-- name: CreateAIConfig :execresult
INSERT INTO ai_configs (provider, model_name, api_key, is_active, config)
VALUES (?, ?, ?, ?, ?)
`

type CreateAIConfigParams struct {
	Provider  string
	ModelName string
	ApiKey    string
	IsActive  sql.NullInt64
	Config    sql.NullString
}

func (q *Queries) CreateAIConfig(ctx context.Context, arg CreateAIConfigParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAIConfig,
		arg.Provider,
		arg.ModelName,
		arg.ApiKey,
		arg.IsActive,
		arg.Config,
	)
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (topic_id, exercise_id, context_type, title) VALUES (?, ?, ?, ?) RETURNING id, topic_id, exercise_id, context_type, title, created_at, updated_at
`

type CreateConversationParams struct {
	TopicID     sql.NullInt64
	ExerciseID  sql.NullInt64
	ContextType sql.NullString
	Title       sql.NullString
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.TopicID,
		arg.ExerciseID,
		arg.ContextType,
		arg.Title,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.ExerciseID,
		&i.ContextType,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, role, content, model_provider, token_count) VALUES (?, ?, ?, ?, ?) RETURNING id, conversation_id, role, content, model_provider, token_count, created_at
`

type CreateMessageParams struct {
	ConversationID int64
	Role           string
	Content        string
	ModelProvider  sql.NullString
	TokenCount     sql.NullInt64
}

type CreateMessageRow struct {
	ID             int64
	ConversationID int64
	Role           string
	Content        string
	ModelProvider  sql.NullString
	TokenCount     sql.NullInt64
	CreatedAt      sql.NullTime
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.ModelProvider,
		arg.TokenCount,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.ModelProvider,
		&i.TokenCount,
		&i.CreatedAt,
	)
	return i, err
}

const createWikiPage = `-- name: CreateWikiPage :execresult
INSERT INTO wiki_pages (title, slug, page_type, content, tags, parent_id, content_status, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWikiPageParams struct {
	Title         string
	Slug          string
	PageType      string
	Content       string
	Tags          sql.NullString
	ParentID      sql.NullInt64
	ContentStatus string
	SortOrder     int64
}

func (q *Queries) CreateWikiPage(ctx context.Context, arg CreateWikiPageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWikiPage,
		arg.Title,
		arg.Slug,
		arg.PageType,
		arg.Content,
		arg.Tags,
		arg.ParentID,
		arg.ContentStatus,
		arg.SortOrder,
	)
}

const deactivateAllConfigs = `-- name: DeactivateAllConfigs :exec
UPDATE ai_configs SET is_active = 0 WHERE is_active = 1
`

func (q *Queries) DeactivateAllConfigs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deactivateAllConfigs)
	return err
}

const deleteWikiPage = `-- name: DeleteWikiPage :exec
DELETE FROM wiki_pages WHERE id = ?
`

func (q *Queries) DeleteWikiPage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWikiPage, id)
	return err
}

const getAIConfigByProvider = `-- name: GetAIConfigByProvider :one
SELECT id, provider, model_name, api_key, is_active, config, created_at, updated_at FROM ai_configs WHERE provider = ? LIMIT 1
`

func (q *Queries) GetAIConfigByProvider(ctx context.Context, provider string) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, getAIConfigByProvider, provider)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelName,
		&i.ApiKey,
		&i.IsActive,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAIConfig = `-- name: GetActiveAIConfig :one
SELECT id, provider, model_name, api_key, is_active, config, created_at, updated_at FROM ai_configs WHERE is_active = 1 LIMIT 1
`

func (q *Queries) GetActiveAIConfig(ctx context.Context) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, getActiveAIConfig)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelName,
		&i.ApiKey,
		&i.IsActive,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllConversations = `-- name: GetAllConversations :many
SELECT id, topic_id, exercise_id, context_type, title, created_at, updated_at FROM conversations ORDER BY updated_at DESC
`

func (q *Queries) GetAllConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getAllConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.ExerciseID,
			&i.ContextType,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExercises = `-- name: GetAllExercises :many
SELECT id, topic_id, type, title, description, difficulty, tags, hints, solution_outline, solution_detail, common_errors, time_complexity_expected, space_complexity_expected, sample_code, created_at, updated_at FROM exercises
`

type GetAllExercisesRow struct {
	ID                      int64
	TopicID                 int64
	Type                    sql.NullString
	Title                   string
	Description             sql.NullString
	Difficulty              sql.NullString
	Tags                    sql.NullString
	Hints                   sql.NullString
	SolutionOutline         sql.NullString
	SolutionDetail          sql.NullString
	CommonErrors            sql.NullString
	TimeComplexityExpected  sql.NullString
	SpaceComplexityExpected sql.NullString
	SampleCode              sql.NullString
	CreatedAt               sql.NullTime
	UpdatedAt               sql.NullTime
}

func (q *Queries) GetAllExercises(ctx context.Context) ([]GetAllExercisesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllExercisesRow
	for rows.Next() {
		var i GetAllExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Tags,
			&i.Hints,
			&i.SolutionOutline,
			&i.SolutionDetail,
			&i.CommonErrors,
			&i.TimeComplexityExpected,
			&i.SpaceComplexityExpected,
			&i.SampleCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTopics = `-- name: GetAllTopics :many
SELECT id, parent_id, name, slug, description, key_points, difficulty, sort_order, content, code_examples, common_mistakes, created_at, updated_at FROM topics ORDER BY sort_order, id
`

type GetAllTopicsRow struct {
	ID             int64
	ParentID       sql.NullInt64
	Name           string
	Slug           string
	Description    sql.NullString
	KeyPoints      sql.NullString
	Difficulty     sql.NullString
	SortOrder      sql.NullInt64
	Content        sql.NullString
	CodeExamples   sql.NullString
	CommonMistakes sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) GetAllTopics(ctx context.Context) ([]GetAllTopicsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTopicsRow
	for rows.Next() {
		var i GetAllTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.KeyPoints,
			&i.Difficulty,
			&i.SortOrder,
			&i.Content,
			&i.CodeExamples,
			&i.CommonMistakes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWikiPages = `-- name: GetAllWikiPages :many

SELECT id, title, slug, page_type, content, tags, parent_id, content_status, sort_order, created_at, updated_at
FROM wiki_pages
ORDER BY sort_order, id
`

type GetAllWikiPagesRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	Content       string
	Tags          sql.NullString
	ParentID      sql.NullInt64
	ContentStatus string
	SortOrder     int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Wiki queries
func (q *Queries) GetAllWikiPages(ctx context.Context) ([]GetAllWikiPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWikiPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWikiPagesRow
	for rows.Next() {
		var i GetAllWikiPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PageType,
			&i.Content,
			&i.Tags,
			&i.ParentID,
			&i.ContentStatus,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, topic_id, exercise_id, context_type, title, created_at, updated_at FROM conversations WHERE id = ?
`

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.ExerciseID,
		&i.ContextType,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmptyWikiPages = `-- name: GetEmptyWikiPages :many
SELECT id, title, slug, parent_id
FROM wiki_pages
WHERE content_status = 'empty'
ORDER BY sort_order, id
`

type GetEmptyWikiPagesRow struct {
	ID       int64
	Title    string
	Slug     string
	ParentID sql.NullInt64
}

func (q *Queries) GetEmptyWikiPages(ctx context.Context) ([]GetEmptyWikiPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEmptyWikiPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmptyWikiPagesRow
	for rows.Next() {
		var i GetEmptyWikiPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, topic_id, type, title, description, difficulty, tags, hints, solution_outline, solution_detail, common_errors, time_complexity_expected, space_complexity_expected, sample_code, created_at, updated_at FROM exercises WHERE id = ?
`

type GetExerciseByIDRow struct {
	ID                      int64
	TopicID                 int64
	Type                    sql.NullString
	Title                   string
	Description             sql.NullString
	Difficulty              sql.NullString
	Tags                    sql.NullString
	Hints                   sql.NullString
	SolutionOutline         sql.NullString
	SolutionDetail          sql.NullString
	CommonErrors            sql.NullString
	TimeComplexityExpected  sql.NullString
	SpaceComplexityExpected sql.NullString
	SampleCode              sql.NullString
	CreatedAt               sql.NullTime
	UpdatedAt               sql.NullTime
}

func (q *Queries) GetExerciseByID(ctx context.Context, id int64) (GetExerciseByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByID, id)
	var i GetExerciseByIDRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Tags,
		&i.Hints,
		&i.SolutionOutline,
		&i.SolutionDetail,
		&i.CommonErrors,
		&i.TimeComplexityExpected,
		&i.SpaceComplexityExpected,
		&i.SampleCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExerciseCountByTopic = `-- name: GetExerciseCountByTopic :many
SELECT topic_id, COUNT(*) as exercise_count FROM exercises
GROUP BY topic_id
`

type GetExerciseCountByTopicRow struct {
	TopicID       int64
	ExerciseCount int64
}

func (q *Queries) GetExerciseCountByTopic(ctx context.Context) ([]GetExerciseCountByTopicRow, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseCountByTopic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseCountByTopicRow
	for rows.Next() {
		var i GetExerciseCountByTopicRow
		if err := rows.Scan(&i.TopicID, &i.ExerciseCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExercisesByTopicID = `-- name: GetExercisesByTopicID :many
SELECT id, topic_id, type, title, description, difficulty, tags, hints, solution_outline, solution_detail, common_errors, time_complexity_expected, space_complexity_expected, sample_code, created_at, updated_at FROM exercises WHERE topic_id = ?
`

type GetExercisesByTopicIDRow struct {
	ID                      int64
	TopicID                 int64
	Type                    sql.NullString
	Title                   string
	Description             sql.NullString
	Difficulty              sql.NullString
	Tags                    sql.NullString
	Hints                   sql.NullString
	SolutionOutline         sql.NullString
	SolutionDetail          sql.NullString
	CommonErrors            sql.NullString
	TimeComplexityExpected  sql.NullString
	SpaceComplexityExpected sql.NullString
	SampleCode              sql.NullString
	CreatedAt               sql.NullTime
	UpdatedAt               sql.NullTime
}

func (q *Queries) GetExercisesByTopicID(ctx context.Context, topicID int64) ([]GetExercisesByTopicIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getExercisesByTopicID, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExercisesByTopicIDRow
	for rows.Next() {
		var i GetExercisesByTopicIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Tags,
			&i.Hints,
			&i.SolutionOutline,
			&i.SolutionDetail,
			&i.CommonErrors,
			&i.TimeComplexityExpected,
			&i.SpaceComplexityExpected,
			&i.SampleCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningRecordByExercise = `-- name: GetLearningRecordByExercise :one
SELECT id, topic_id, exercise_id, status, mastery_level, notes, last_reviewed_at, review_count, created_at, updated_at FROM learning_records WHERE exercise_id = ?
`

func (q *Queries) GetLearningRecordByExercise(ctx context.Context, exerciseID sql.NullInt64) (LearningRecord, error) {
	row := q.db.QueryRowContext(ctx, getLearningRecordByExercise, exerciseID)
	var i LearningRecord
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.ExerciseID,
		&i.Status,
		&i.MasteryLevel,
		&i.Notes,
		&i.LastReviewedAt,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLearningRecordByTopic = `-- name: GetLearningRecordByTopic :one
SELECT id, topic_id, exercise_id, status, mastery_level, notes, last_reviewed_at, review_count, created_at, updated_at FROM learning_records WHERE topic_id = ?
`

func (q *Queries) GetLearningRecordByTopic(ctx context.Context, topicID sql.NullInt64) (LearningRecord, error) {
	row := q.db.QueryRowContext(ctx, getLearningRecordByTopic, topicID)
	var i LearningRecord
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.ExerciseID,
		&i.Status,
		&i.MasteryLevel,
		&i.Notes,
		&i.LastReviewedAt,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLearningRecords = `-- name: GetLearningRecords :many
SELECT id, topic_id, exercise_id, status, mastery_level, notes, last_reviewed_at, review_count, created_at, updated_at FROM learning_records
`

func (q *Queries) GetLearningRecords(ctx context.Context) ([]LearningRecord, error) {
	rows, err := q.db.QueryContext(ctx, getLearningRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningRecord
	for rows.Next() {
		var i LearningRecord
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.ExerciseID,
			&i.Status,
			&i.MasteryLevel,
			&i.Notes,
			&i.LastReviewedAt,
			&i.ReviewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT id, conversation_id, role, content, model_provider, token_count, created_at FROM messages WHERE conversation_id = ? ORDER BY created_at
`

type GetMessagesByConversationRow struct {
	ID             int64
	ConversationID int64
	Role           string
	Content        string
	ModelProvider  sql.NullString
	TokenCount     sql.NullInt64
	CreatedAt      sql.NullTime
}

func (q *Queries) GetMessagesByConversation(ctx context.Context, conversationID int64) ([]GetMessagesByConversationRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByConversationRow
	for rows.Next() {
		var i GetMessagesByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ModelProvider,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextTopic = `-- name: GetNextTopic :one
SELECT t1.id, t1.slug, t1.name, t1.difficulty FROM topics t1
WHERE t1.parent_id = (SELECT t2.parent_id FROM topics t2 WHERE t2.slug = ?)
  AND t1.sort_order > (SELECT t3.sort_order FROM topics t3 WHERE t3.slug = ?)
ORDER BY t1.sort_order ASC
LIMIT 1
`

type GetNextTopicParams struct {
	Slug   string
	Slug_2 string
}

type GetNextTopicRow struct {
	ID         int64
	Slug       string
	Name       string
	Difficulty sql.NullString
}

func (q *Queries) GetNextTopic(ctx context.Context, arg GetNextTopicParams) (GetNextTopicRow, error) {
	row := q.db.QueryRowContext(ctx, getNextTopic, arg.Slug, arg.Slug_2)
	var i GetNextTopicRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Difficulty,
	)
	return i, err
}

const getOverviewPage = `-- name: GetOverviewPage :one
SELECT id, title, slug, page_type, content, tags, parent_id, content_status, sort_order, created_at, updated_at
FROM wiki_pages
WHERE page_type = 'overview' LIMIT 1
`

type GetOverviewPageRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	Content       string
	Tags          sql.NullString
	ParentID      sql.NullInt64
	ContentStatus string
	SortOrder     int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetOverviewPage(ctx context.Context) (GetOverviewPageRow, error) {
	row := q.db.QueryRowContext(ctx, getOverviewPage)
	var i GetOverviewPageRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PageType,
		&i.Content,
		&i.Tags,
		&i.ParentID,
		&i.ContentStatus,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPagesNeedingSummary = `-- name: GetPagesNeedingSummary :many
SELECT id, title, content
FROM wiki_pages
WHERE summary_status = 'empty' AND content != ''
ORDER BY id
LIMIT ?
`

type GetPagesNeedingSummaryRow struct {
	ID      int64
	Title   string
	Content string
}

func (q *Queries) GetPagesNeedingSummary(ctx context.Context, limit int64) ([]GetPagesNeedingSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getPagesNeedingSummary, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPagesNeedingSummaryRow
	for rows.Next() {
		var i GetPagesNeedingSummaryRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrevTopic = `-- name: GetPrevTopic :one
SELECT t1.id, t1.slug, t1.name, t1.difficulty FROM topics t1
WHERE t1.parent_id = (SELECT t2.parent_id FROM topics t2 WHERE t2.slug = ?)
  AND t1.sort_order < (SELECT t3.sort_order FROM topics t3 WHERE t3.slug = ?)
ORDER BY t1.sort_order DESC
LIMIT 1
`

type GetPrevTopicParams struct {
	Slug   string
	Slug_2 string
}

type GetPrevTopicRow struct {
	ID         int64
	Slug       string
	Name       string
	Difficulty sql.NullString
}

func (q *Queries) GetPrevTopic(ctx context.Context, arg GetPrevTopicParams) (GetPrevTopicRow, error) {
	row := q.db.QueryRowContext(ctx, getPrevTopic, arg.Slug, arg.Slug_2)
	var i GetPrevTopicRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Difficulty,
	)
	return i, err
}

const getRecentWikiLog = `-- name: GetRecentWikiLog :many
SELECT id, action, page_id, page_title, page_path, source, summary, created_at
FROM wiki_log
WHERE created_at > ?
ORDER BY created_at DESC
LIMIT ?
`

type GetRecentWikiLogParams struct {
	CreatedAt time.Time
	Limit     int64
}

func (q *Queries) GetRecentWikiLog(ctx context.Context, arg GetRecentWikiLogParams) ([]WikiLog, error) {
	rows, err := q.db.QueryContext(ctx, getRecentWikiLog, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WikiLog
	for rows.Next() {
		var i WikiLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.PageID,
			&i.PageTitle,
			&i.PagePath,
			&i.Source,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentWikiLogForPage = `-- name: GetRecentWikiLogForPage :many
SELECT id, action, page_id, page_title, page_path, source, summary, created_at
FROM wiki_log
WHERE page_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetRecentWikiLogForPageParams struct {
	PageID sql.NullInt64
	Limit  int64
}

func (q *Queries) GetRecentWikiLogForPage(ctx context.Context, arg GetRecentWikiLogForPageParams) ([]WikiLog, error) {
	rows, err := q.db.QueryContext(ctx, getRecentWikiLogForPage, arg.PageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WikiLog
	for rows.Next() {
		var i WikiLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.PageID,
			&i.PageTitle,
			&i.PagePath,
			&i.Source,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyUpdatedWikiPages = `-- name: GetRecentlyUpdatedWikiPages :many
SELECT id, title, slug, page_type, content_status, updated_at
FROM wiki_pages
WHERE page_type != 'overview'
ORDER BY updated_at DESC
LIMIT 10
`

type GetRecentlyUpdatedWikiPagesRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	ContentStatus string
	UpdatedAt     time.Time
}

func (q *Queries) GetRecentlyUpdatedWikiPages(ctx context.Context) ([]GetRecentlyUpdatedWikiPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentlyUpdatedWikiPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyUpdatedWikiPagesRow
	for rows.Next() {
		var i GetRecentlyUpdatedWikiPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PageType,
			&i.ContentStatus,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtreePages = `-- name: GetSubtreePages :many
SELECT id, title, slug, page_type, content_status, parent_id, sort_order, path
FROM wiki_pages
WHERE path LIKE ?1 || '%'
ORDER BY path, sort_order, id
`

type GetSubtreePagesRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	ContentStatus string
	ParentID      sql.NullInt64
	SortOrder     int64
	Path          string
}

func (q *Queries) GetSubtreePages(ctx context.Context, prefix sql.NullString) ([]GetSubtreePagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubtreePages, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubtreePagesRow
	for rows.Next() {
		var i GetSubtreePagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PageType,
			&i.ContentStatus,
			&i.ParentID,
			&i.SortOrder,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicAncestors = `-- name: GetTopicAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT t.id, t.slug, t.name, t.parent_id, 0 as depth FROM topics t WHERE t.slug = ?
    UNION ALL
    SELECT p.id, p.slug, p.name, p.parent_id, a.depth + 1
    FROM topics p JOIN ancestors a ON p.id = a.parent_id
)
SELECT id, slug, name FROM ancestors WHERE depth > 0 ORDER BY depth DESC
`

type GetTopicAncestorsRow struct {
	ID   int64
	Slug string
	Name string
}

func (q *Queries) GetTopicAncestors(ctx context.Context, slug string) ([]GetTopicAncestorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopicAncestors, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopicAncestorsRow
	for rows.Next() {
		var i GetTopicAncestorsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, parent_id, name, slug, description, key_points, difficulty, sort_order, content, code_examples, common_mistakes, created_at, updated_at FROM topics WHERE id = ?
`

type GetTopicByIDRow struct {
	ID             int64
	ParentID       sql.NullInt64
	Name           string
	Slug           string
	Description    sql.NullString
	KeyPoints      sql.NullString
	Difficulty     sql.NullString
	SortOrder      sql.NullInt64
	Content        sql.NullString
	CodeExamples   sql.NullString
	CommonMistakes sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) GetTopicByID(ctx context.Context, id int64) (GetTopicByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTopicByID, id)
	var i GetTopicByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.KeyPoints,
		&i.Difficulty,
		&i.SortOrder,
		&i.Content,
		&i.CodeExamples,
		&i.CommonMistakes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopicBySlug = `-- name: GetTopicBySlug :one
SELECT id, parent_id, name, slug, description, key_points, difficulty, sort_order, content, code_examples, common_mistakes, created_at, updated_at FROM topics WHERE slug = ?
`

type GetTopicBySlugRow struct {
	ID             int64
	ParentID       sql.NullInt64
	Name           string
	Slug           string
	Description    sql.NullString
	KeyPoints      sql.NullString
	Difficulty     sql.NullString
	SortOrder      sql.NullInt64
	Content        sql.NullString
	CodeExamples   sql.NullString
	CommonMistakes sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) GetTopicBySlug(ctx context.Context, slug string) (GetTopicBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getTopicBySlug, slug)
	var i GetTopicBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.KeyPoints,
		&i.Difficulty,
		&i.SortOrder,
		&i.Content,
		&i.CodeExamples,
		&i.CommonMistakes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWikiLogBetween = `-- name: GetWikiLogBetween :many
SELECT id, action, page_id, page_title, page_path, source, summary, created_at
FROM wiki_log
WHERE created_at > ? AND created_at < ?
ORDER BY created_at DESC
LIMIT ?
`

type GetWikiLogBetweenParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int64
}

func (q *Queries) GetWikiLogBetween(ctx context.Context, arg GetWikiLogBetweenParams) ([]WikiLog, error) {
	rows, err := q.db.QueryContext(ctx, getWikiLogBetween, arg.CreatedAt, arg.CreatedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WikiLog
	for rows.Next() {
		var i WikiLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.PageID,
			&i.PageTitle,
			&i.PagePath,
			&i.Source,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWikiPageByID = `-- name: GetWikiPageByID :one
SELECT id, title, slug, page_type, content, tags, parent_id, path, links, backlinks, content_status, sort_order, created_at, updated_at, summary, summary_status, summary_generated_at, summary_content_hash, link_count, backlink_count, tags_normalized FROM wiki_pages WHERE id = ?
`

func (q *Queries) GetWikiPageByID(ctx context.Context, id int64) (WikiPage, error) {
	row := q.db.QueryRowContext(ctx, getWikiPageByID, id)
	var i WikiPage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PageType,
		&i.Content,
		&i.Tags,
		&i.ParentID,
		&i.Path,
		&i.Links,
		&i.Backlinks,
		&i.ContentStatus,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.SummaryStatus,
		&i.SummaryGeneratedAt,
		&i.SummaryContentHash,
		&i.LinkCount,
		&i.BacklinkCount,
		&i.TagsNormalized,
	)
	return i, err
}

const getWikiPageBySlug = `-- name: GetWikiPageBySlug :one
SELECT id, title, slug, page_type, content, tags, parent_id, content_status, sort_order, created_at, updated_at
FROM wiki_pages
WHERE slug = ?
`

type GetWikiPageBySlugRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	Content       string
	Tags          sql.NullString
	ParentID      sql.NullInt64
	ContentStatus string
	SortOrder     int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetWikiPageBySlug(ctx context.Context, slug string) (GetWikiPageBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getWikiPageBySlug, slug)
	var i GetWikiPageBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PageType,
		&i.Content,
		&i.Tags,
		&i.ParentID,
		&i.ContentStatus,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWikiPageByTitle = `-- name: GetWikiPageByTitle :one
SELECT id, title, slug, page_type, content, tags, parent_id, path, links, backlinks, content_status, sort_order, created_at, updated_at FROM wiki_pages WHERE title = ? LIMIT 1
`

type GetWikiPageByTitleRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	Content       string
	Tags          sql.NullString
	ParentID      sql.NullInt64
	Path          string
	Links         string
	Backlinks     string
	ContentStatus string
	SortOrder     int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetWikiPageByTitle(ctx context.Context, title string) (GetWikiPageByTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getWikiPageByTitle, title)
	var i GetWikiPageByTitleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PageType,
		&i.Content,
		&i.Tags,
		&i.ParentID,
		&i.Path,
		&i.Links,
		&i.Backlinks,
		&i.ContentStatus,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWikiPageChildren = `-- name: GetWikiPageChildren :many
SELECT id, title, slug, page_type, content_status, sort_order
FROM wiki_pages
WHERE parent_id = ?
ORDER BY sort_order, id
`

type GetWikiPageChildrenRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	ContentStatus string
	SortOrder     int64
}

func (q *Queries) GetWikiPageChildren(ctx context.Context, parentID sql.NullInt64) ([]GetWikiPageChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, getWikiPageChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWikiPageChildrenRow
	for rows.Next() {
		var i GetWikiPageChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PageType,
			&i.ContentStatus,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWikiPagePathByID = `-- name: GetWikiPagePathByID :one
SELECT path FROM wiki_pages WHERE id = ?
`

func (q *Queries) GetWikiPagePathByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getWikiPagePathByID, id)
	var path string
	err := row.Scan(&path)
	return path, err
}

const getWikiPageTree = `-- name: GetWikiPageTree :many
SELECT id, title, slug, page_type, content_status, parent_id, sort_order, path
FROM wiki_pages
ORDER BY sort_order, id
`

type GetWikiPageTreeRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	ContentStatus string
	ParentID      sql.NullInt64
	SortOrder     int64
	Path          string
}

func (q *Queries) GetWikiPageTree(ctx context.Context) ([]GetWikiPageTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, getWikiPageTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWikiPageTreeRow
	for rows.Next() {
		var i GetWikiPageTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PageType,
			&i.ContentStatus,
			&i.ParentID,
			&i.SortOrder,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWikiLog = `-- name: InsertWikiLog :exec
INSERT INTO wiki_log (action, page_id, page_title, page_path, source, summary)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertWikiLogParams struct {
	Action    string
	PageID    sql.NullInt64
	PageTitle string
	PagePath  sql.NullString
	Source    string
	Summary   sql.NullString
}

func (q *Queries) InsertWikiLog(ctx context.Context, arg InsertWikiLogParams) error {
	_, err := q.db.ExecContext(ctx, insertWikiLog,
		arg.Action,
		arg.PageID,
		arg.PageTitle,
		arg.PagePath,
		arg.Source,
		arg.Summary,
	)
	return err
}

const listPendingSummaries = `-- name: ListPendingSummaries :many
SELECT id, title, content
FROM wiki_pages
WHERE summary_status IN ('pending', 'failed')
ORDER BY summary_status DESC, id
LIMIT ?
`

type ListPendingSummariesRow struct {
	ID      int64
	Title   string
	Content string
}

func (q *Queries) ListPendingSummaries(ctx context.Context, limit int64) ([]ListPendingSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingSummaries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSummariesRow
	for rows.Next() {
		var i ListPendingSummariesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSummaryEmpty = `-- name: MarkSummaryEmpty :exec
UPDATE wiki_pages
SET summary_status = 'empty',
    summary_content_hash = NULL,
    summary_generated_at = NULL
WHERE id = ?
`

func (q *Queries) MarkSummaryEmpty(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSummaryEmpty, id)
	return err
}

const markSummaryFailed = `-- name: MarkSummaryFailed :exec
UPDATE wiki_pages
SET summary_status = 'failed',
    summary_generated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkSummaryFailed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSummaryFailed, id)
	return err
}

const markSummaryPending = `-- name: MarkSummaryPending :exec
UPDATE wiki_pages
SET summary_status = 'pending',
    summary_content_hash = NULL
WHERE id = ?
`

func (q *Queries) MarkSummaryPending(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSummaryPending, id)
	return err
}

const searchWikiPages = `-- name: SearchWikiPages :many
SELECT id, title, slug, page_type, content, tags, parent_id, content_status, sort_order, created_at, updated_at
FROM wiki_pages
WHERE title LIKE '%' || ?1 || '%' OR content LIKE '%' || ?1 || '%'
ORDER BY sort_order, id
`

type SearchWikiPagesRow struct {
	ID            int64
	Title         string
	Slug          string
	PageType      string
	Content       string
	Tags          sql.NullString
	ParentID      sql.NullInt64
	ContentStatus string
	SortOrder     int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) SearchWikiPages(ctx context.Context, query sql.NullString) ([]SearchWikiPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchWikiPages, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchWikiPagesRow
	for rows.Next() {
		var i SearchWikiPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PageType,
			&i.Content,
			&i.Tags,
			&i.ParentID,
			&i.ContentStatus,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIConfig = `-- name: UpdateAIConfig :exec
UPDATE ai_configs
SET provider = ?, model_name = ?, api_key = ?, is_active = ?, config = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAIConfigParams struct {
	Provider  string
	ModelName string
	ApiKey    string
	IsActive  sql.NullInt64
	Config    sql.NullString
	ID        int64
}

func (q *Queries) UpdateAIConfig(ctx context.Context, arg UpdateAIConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateAIConfig,
		arg.Provider,
		arg.ModelName,
		arg.ApiKey,
		arg.IsActive,
		arg.Config,
		arg.ID,
	)
	return err
}

const updateExerciseErrors = `-- name: UpdateExerciseErrors :exec
UPDATE exercises SET common_errors = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateExerciseErrorsParams struct {
	CommonErrors sql.NullString
	ID           int64
}

func (q *Queries) UpdateExerciseErrors(ctx context.Context, arg UpdateExerciseErrorsParams) error {
	_, err := q.db.ExecContext(ctx, updateExerciseErrors, arg.CommonErrors, arg.ID)
	return err
}

const updateExerciseSolution = `-- name: UpdateExerciseSolution :exec
UPDATE exercises SET solution_detail = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateExerciseSolutionParams struct {
	SolutionDetail sql.NullString
	ID             int64
}

func (q *Queries) UpdateExerciseSolution(ctx context.Context, arg UpdateExerciseSolutionParams) error {
	_, err := q.db.ExecContext(ctx, updateExerciseSolution, arg.SolutionDetail, arg.ID)
	return err
}

const updatePageSummary = `-- name: UpdatePageSummary :exec
UPDATE wiki_pages
SET summary = ?,
    summary_status = 'ready',
    summary_content_hash = ?,
    summary_generated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePageSummaryParams struct {
	Summary            string
	SummaryContentHash sql.NullString
	ID                 int64
}

func (q *Queries) UpdatePageSummary(ctx context.Context, arg UpdatePageSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updatePageSummary, arg.Summary, arg.SummaryContentHash, arg.ID)
	return err
}

const updateTopicContent = `-- name: UpdateTopicContent :exec
UPDATE topics SET content = ?, code_examples = ?, common_mistakes = ?, updated_at = CURRENT_TIMESTAMP WHERE slug = ?
`

type UpdateTopicContentParams struct {
	Content        sql.NullString
	CodeExamples   sql.NullString
	CommonMistakes sql.NullString
	Slug           string
}

func (q *Queries) UpdateTopicContent(ctx context.Context, arg UpdateTopicContentParams) error {
	_, err := q.db.ExecContext(ctx, updateTopicContent,
		arg.Content,
		arg.CodeExamples,
		arg.CommonMistakes,
		arg.Slug,
	)
	return err
}

const updateWikiPage = `-- name: UpdateWikiPage :exec
UPDATE wiki_pages
SET title = ?, slug = ?, page_type = ?, content = ?, tags = ?, parent_id = ?, content_status = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWikiPageParams struct {
	Title         string
	Slug          string
	PageType      string
	Content       string
	Tags          sql.NullString
	ParentID      sql.NullInt64
	ContentStatus string
	SortOrder     int64
	ID            int64
}

func (q *Queries) UpdateWikiPage(ctx context.Context, arg UpdateWikiPageParams) error {
	_, err := q.db.ExecContext(ctx, updateWikiPage,
		arg.Title,
		arg.Slug,
		arg.PageType,
		arg.Content,
		arg.Tags,
		arg.ParentID,
		arg.ContentStatus,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateWikiPageContent = `-- name: UpdateWikiPageContent :exec
UPDATE wiki_pages
SET content = ?, content_status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWikiPageContentParams struct {
	Content       string
	ContentStatus string
	ID            int64
}

func (q *Queries) UpdateWikiPageContent(ctx context.Context, arg UpdateWikiPageContentParams) error {
	_, err := q.db.ExecContext(ctx, updateWikiPageContent, arg.Content, arg.ContentStatus, arg.ID)
	return err
}

const updateWikiPagePath = `-- name: UpdateWikiPagePath :exec
UPDATE wiki_pages SET path = ? WHERE id = ?
`

type UpdateWikiPagePathParams struct {
	Path string
	ID   int64
}

func (q *Queries) UpdateWikiPagePath(ctx context.Context, arg UpdateWikiPagePathParams) error {
	_, err := q.db.ExecContext(ctx, updateWikiPagePath, arg.Path, arg.ID)
	return err
}

const upsertLearningRecord = `-- name: UpsertLearningRecord :exec
INSERT INTO learning_records (topic_id, exercise_id, status, mastery_level, notes, last_reviewed_at, review_count)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    topic_id = excluded.topic_id,
    exercise_id = excluded.exercise_id,
    status = excluded.status,
    mastery_level = excluded.mastery_level,
    notes = excluded.notes,
    last_reviewed_at = excluded.last_reviewed_at,
    review_count = excluded.review_count,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertLearningRecordParams struct {
	TopicID        sql.NullInt64
	ExerciseID     sql.NullInt64
	Status         sql.NullString
	MasteryLevel   sql.NullInt64
	Notes          sql.NullString
	LastReviewedAt sql.NullTime
	ReviewCount    sql.NullInt64
}

func (q *Queries) UpsertLearningRecord(ctx context.Context, arg UpsertLearningRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertLearningRecord,
		arg.TopicID,
		arg.ExerciseID,
		arg.Status,
		arg.MasteryLevel,
		arg.Notes,
		arg.LastReviewedAt,
		arg.ReviewCount,
	)
	return err
}
