// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package model

import (
	"context"
	"database/sql"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (topic_id, exercise_id, context_type, title) VALUES (?, ?, ?, ?) RETURNING id, topic_id, exercise_id, context_type, title, created_at, updated_at
`

type CreateConversationParams struct {
	TopicID     sql.NullInt64
	ExerciseID  sql.NullInt64
	ContextType sql.NullString
	Title       sql.NullString
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.TopicID,
		arg.ExerciseID,
		arg.ContextType,
		arg.Title,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.ExerciseID,
		&i.ContextType,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, role, content, model_provider, token_count) VALUES (?, ?, ?, ?, ?) RETURNING id, conversation_id, role, content, model_provider, token_count, created_at
`

type CreateMessageParams struct {
	ConversationID int64
	Role           string
	Content        string
	ModelProvider  sql.NullString
	TokenCount     sql.NullInt64
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.ModelProvider,
		arg.TokenCount,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.ModelProvider,
		&i.TokenCount,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAIConfig = `-- name: GetActiveAIConfig :one
SELECT id, provider, model_name, api_key, is_active, config, created_at, updated_at FROM ai_configs WHERE is_active = 1
`

func (q *Queries) GetActiveAIConfig(ctx context.Context) (AiConfig, error) {
	row := q.db.QueryRowContext(ctx, getActiveAIConfig)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelName,
		&i.ApiKey,
		&i.IsActive,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllConversations = `-- name: GetAllConversations :many
SELECT id, topic_id, exercise_id, context_type, title, created_at, updated_at FROM conversations ORDER BY updated_at DESC
`

func (q *Queries) GetAllConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getAllConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.ExerciseID,
			&i.ContextType,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExercises = `-- name: GetAllExercises :many
SELECT id, topic_id, type, title, description, difficulty, tags, hints, solution_outline, time_complexity_expected, space_complexity_expected, sample_code, created_at, updated_at FROM exercises
`

func (q *Queries) GetAllExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getAllExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Tags,
			&i.Hints,
			&i.SolutionOutline,
			&i.TimeComplexityExpected,
			&i.SpaceComplexityExpected,
			&i.SampleCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTopics = `-- name: GetAllTopics :many
SELECT id, parent_id, name, slug, description, key_points, difficulty, sort_order, created_at, updated_at FROM topics ORDER BY sort_order, id
`

func (q *Queries) GetAllTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.QueryContext(ctx, getAllTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.KeyPoints,
			&i.Difficulty,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, topic_id, exercise_id, context_type, title, created_at, updated_at FROM conversations WHERE id = ?
`

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.ExerciseID,
		&i.ContextType,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, topic_id, type, title, description, difficulty, tags, hints, solution_outline, time_complexity_expected, space_complexity_expected, sample_code, created_at, updated_at FROM exercises WHERE id = ?
`

func (q *Queries) GetExerciseByID(ctx context.Context, id int64) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Tags,
		&i.Hints,
		&i.SolutionOutline,
		&i.TimeComplexityExpected,
		&i.SpaceComplexityExpected,
		&i.SampleCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExercisesByTopicID = `-- name: GetExercisesByTopicID :many
SELECT id, topic_id, type, title, description, difficulty, tags, hints, solution_outline, time_complexity_expected, space_complexity_expected, sample_code, created_at, updated_at FROM exercises WHERE topic_id = ?
`

func (q *Queries) GetExercisesByTopicID(ctx context.Context, topicID int64) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getExercisesByTopicID, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Tags,
			&i.Hints,
			&i.SolutionOutline,
			&i.TimeComplexityExpected,
			&i.SpaceComplexityExpected,
			&i.SampleCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningRecordByExercise = `-- name: GetLearningRecordByExercise :one
SELECT id, topic_id, exercise_id, status, mastery_level, notes, last_reviewed_at, review_count, created_at, updated_at FROM learning_records WHERE exercise_id = ?
`

func (q *Queries) GetLearningRecordByExercise(ctx context.Context, exerciseID sql.NullInt64) (LearningRecord, error) {
	row := q.db.QueryRowContext(ctx, getLearningRecordByExercise, exerciseID)
	var i LearningRecord
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.ExerciseID,
		&i.Status,
		&i.MasteryLevel,
		&i.Notes,
		&i.LastReviewedAt,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLearningRecordByTopic = `-- name: GetLearningRecordByTopic :one
SELECT id, topic_id, exercise_id, status, mastery_level, notes, last_reviewed_at, review_count, created_at, updated_at FROM learning_records WHERE topic_id = ?
`

func (q *Queries) GetLearningRecordByTopic(ctx context.Context, topicID sql.NullInt64) (LearningRecord, error) {
	row := q.db.QueryRowContext(ctx, getLearningRecordByTopic, topicID)
	var i LearningRecord
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.ExerciseID,
		&i.Status,
		&i.MasteryLevel,
		&i.Notes,
		&i.LastReviewedAt,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLearningRecords = `-- name: GetLearningRecords :many
SELECT id, topic_id, exercise_id, status, mastery_level, notes, last_reviewed_at, review_count, created_at, updated_at FROM learning_records
`

func (q *Queries) GetLearningRecords(ctx context.Context) ([]LearningRecord, error) {
	rows, err := q.db.QueryContext(ctx, getLearningRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningRecord
	for rows.Next() {
		var i LearningRecord
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.ExerciseID,
			&i.Status,
			&i.MasteryLevel,
			&i.Notes,
			&i.LastReviewedAt,
			&i.ReviewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT id, conversation_id, role, content, model_provider, token_count, created_at FROM messages WHERE conversation_id = ? ORDER BY created_at
`

func (q *Queries) GetMessagesByConversation(ctx context.Context, conversationID int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ModelProvider,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, parent_id, name, slug, description, key_points, difficulty, sort_order, created_at, updated_at FROM topics WHERE id = ?
`

func (q *Queries) GetTopicByID(ctx context.Context, id int64) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.KeyPoints,
		&i.Difficulty,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopicBySlug = `-- name: GetTopicBySlug :one
SELECT id, parent_id, name, slug, description, key_points, difficulty, sort_order, created_at, updated_at FROM topics WHERE slug = ?
`

func (q *Queries) GetTopicBySlug(ctx context.Context, slug string) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopicBySlug, slug)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.KeyPoints,
		&i.Difficulty,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAIConfig = `-- name: UpsertAIConfig :exec
INSERT INTO ai_configs (provider, model_name, api_key, is_active, config)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    provider = excluded.provider,
    model_name = excluded.model_name,
    api_key = excluded.api_key,
    is_active = excluded.is_active,
    config = excluded.config,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertAIConfigParams struct {
	Provider  string
	ModelName string
	ApiKey    string
	IsActive  sql.NullInt64
	Config    sql.NullString
}

func (q *Queries) UpsertAIConfig(ctx context.Context, arg UpsertAIConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertAIConfig,
		arg.Provider,
		arg.ModelName,
		arg.ApiKey,
		arg.IsActive,
		arg.Config,
	)
	return err
}

const upsertLearningRecord = `-- name: UpsertLearningRecord :exec
INSERT INTO learning_records (topic_id, exercise_id, status, mastery_level, notes, last_reviewed_at, review_count)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    topic_id = excluded.topic_id,
    exercise_id = excluded.exercise_id,
    status = excluded.status,
    mastery_level = excluded.mastery_level,
    notes = excluded.notes,
    last_reviewed_at = excluded.last_reviewed_at,
    review_count = excluded.review_count,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertLearningRecordParams struct {
	TopicID        sql.NullInt64
	ExerciseID     sql.NullInt64
	Status         sql.NullString
	MasteryLevel   sql.NullInt64
	Notes          sql.NullString
	LastReviewedAt sql.NullTime
	ReviewCount    sql.NullInt64
}

func (q *Queries) UpsertLearningRecord(ctx context.Context, arg UpsertLearningRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertLearningRecord,
		arg.TopicID,
		arg.ExerciseID,
		arg.Status,
		arg.MasteryLevel,
		arg.Notes,
		arg.LastReviewedAt,
		arg.ReviewCount,
	)
	return err
}
